include:
  - path: ./compose/postgres.yml
    project_directory: .
  - path: ./compose/postgres-migrate.yml
    project_directory: .
  - path: ./compose/tor.yml
    project_directory: .
  - path: ./compose/crawler.yml
    project_directory: .
  - path: ./compose/api.yml
    project_directory: .

networks:
  default:
    name: btc-network_default

volumes:
  cargo-git:
  cargo-registry:
  cargo-target:
  tor-data:
